site_name: ITSec
site_url: http://itsec.aria-network.com/
nav:
  - Home: index.md
  - HTB Academy:
    - 'Pentesting Basics': 'htb-academy/pentesting_basics.md'
    - 'Web Requests': 'htb-academy/web_requests.md'
    - 'Javascript Deobfuscation': 'htb-academy/javascript_deobfuscation.md'
    - 'Network Enumeration with Nmap': 'htb-academy/network_enumeration_with_nmap.md' 
    - 'Template': 'thm/template.md'
  - overthewire.org:
    - Bandit:
      - Level 0-10:
        - 'Level 0': 'overthewire/bandit/level0.md'
        - 'Level 0-1': 'overthewire/bandit/level0-1.md'
        - 'Level 1-2': 'overthewire/bandit/level1-2.md'
        - 'Level 2-3': 'overthewire/bandit/level2-3.md'
        - 'Level 3-4': 'overthewire/bandit/level3-4.md'
        - 'Level 4-5': 'overthewire/bandit/level4-5.md'
        - 'Level 5-6': 'overthewire/bandit/level5-6.md'
        - 'Level 6-7': 'overthewire/bandit/level6-7.md'
        - 'Level 7-8': 'overthewire/bandit/level7-8.md'
        - 'Level 8-9': 'overthewire/bandit/level8-9.md'
        - 'Level 9-10': 'overthewire/bandit/level9-10.md'
      - Level 11-20:
        - 'Level 10-11': 'overthewire/bandit/level10-11.md'
        - 'Level 11-12': 'overthewire/bandit/level11-12.md'
        - 'Level 12-13': 'overthewire/bandit/level12-13.md'
        - 'Level 13-14': 'overthewire/bandit/level13-14.md'
        - 'Level 14-15': 'overthewire/bandit/level14-15.md'
        - 'Level 15-16': 'overthewire/bandit/level15-16.md'
        - 'Level 16-17': 'overthewire/bandit/level16-17.md'
        - 'Level 17-18': 'overthewire/bandit/level17-18.md'
        - 'Level 18-19': 'overthewire/bandit/level18-19.md'
        - 'Level 19-20': 'overthewire/bandit/level19-20.md'
      - Level 21-30:
        - 'Level 20-21': 'overthewire/bandit/level20-21.md'
        - 'Level 21-22': 'overthewire/bandit/level21-22.md'
        - 'Level 22-23': 'overthewire/bandit/level22-23.md'
        - 'Level 23-24': 'overthewire/bandit/level23-24.md'
        - 'Level 24-25': 'overthewire/bandit/level24-25.md'
        - 'Level 25-26': 'overthewire/bandit/level25-26.md'
        - 'Level 26-27': 'overthewire/bandit/level26-27.md'
        - 'Level 27-28': 'overthewire/bandit/level27-28.md'
        - 'Level 28-29': 'overthewire/bandit/level28-29.md'
        - 'Level 29-30': 'overthewire/bandit/level29-30.md'
      - Level 31-33:
        - 'Level 30-31': 'overthewire/bandit/level30-31.md'
        - 'Level 31-32': 'overthewire/bandit/level31-32.md'
        - 'Level 32-33': 'overthewire/bandit/level32-33.md'
    - Natas:
      - 'Level 1-2': 'overthewire/natas/levoel1-2.md'
  - CTF:
    - HTB:
      - Easy:
        - 'Nibbles': 'ctf-boxes/htb/easy/nibbles/nibbles.md'
    - Vulnhub:
      - Easy:
        - 'Jangow': 'ctf-boxes/vulnhub/easy/jangow/jangow.md'
    - THM:
      - Easy:
        - 'EasyPeasy': 'ctf-boxes/thm/easy/easypeasy/easypeasy.md'
  - Tools:
    - 'tmux': 'tools/tmux.md'
    - 'ffuf': 'tools/ffuf.md'
  - Cheatsheets:
    - 'Basic Linux Tools': 'cheatsheets/cheatsheet_basic_linux_tools.md'
    - 'Basic Pentesting': 'cheatsheets/cheatsheet_basic_pentesting.md'
    - 'curl': 'cheatsheets/cheatsheet_curl.md'
    - 'nmap': 'cheatsheets/cheatsheet_nmap.md'
  # - Python:
  #   - 'klase': 'ifka/klase.md'
  #   - 'Gotov zadatak': 'ifka/klase_final.md'
  #   - 'Geometrijski likovi': 'ifka/geometrijski_lik.md'
# use_pygments: true
markdown_extensions:
  - pymdownx.highlight:
      linenums: true  
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true   
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html


extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      # accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - navigation.sections
    - navigation.top
    - content.code.annotate
extra:
  disqus: 'itsec-2'
plugins:
  - search
